services:
  postgres:
    image: postgres:16
    container_name: booking-db
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: bookinguser
      POSTGRES_PASSWORD: bookingpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
